// End-to-end engine test. Runs against a fresh fake home folder; never touches real config.
const fs = require('fs'), path = require('path'), os = require('os'), assert = require('assert');
const H = fs.mkdtempSync(path.join(os.tmpdir(), 'agentdeck-home-'));
process.env.USERPROFILE = H; process.env.HOME = H; process.env.APPDATA = path.join(H, 'AppData', 'Roaming');
for (const d of ['.claude/projects/p1', 'proj', '.codex', '.gemini']) fs.mkdirSync(path.join(H, d), { recursive: true });
fs.writeFileSync(path.join(H,'.claude/projects/p1/a.jsonl'),JSON.stringify({type:'user',cwd:path.join(H,'proj')})+'\n');
fs.writeFileSync(path.join(H,'.claude/settings.json'),JSON.stringify({permissions:{allow:['Bash(ls)']},env:{FOO:'1'}},null,2));
fs.writeFileSync(path.join(H,'.claude/CLAUDE.md'),'# My rules\n\n- keep this\n');
fs.writeFileSync(path.join(H,'.codex/config.toml'),'model = "gpt-5"\n\n[projects.\''+path.join(H,'proj')+'\']\ntrust_level = "trusted"\n');
const c=require('../lib/core');
let s=c.scan();
const on=s.harnesses.filter(h=>h.installed).map(h=>h.id);
assert.deepStrictEqual(on.sort(),['claude','codex','gemini']);
const proj=s.harnesses.find(h=>h.id==='claude').projects[0].path;
assert.strictEqual(s.harnesses.find(h=>h.id==='codex').projects[0].path,proj);
const vals={verbosity:'terse',readFirst:true,lengthCap:'40',custom:'Use pnpm\n- Never push'};
let plan=c.planProfile({harnesses:['claude','codex'],project:'',values:vals});
assert.strictEqual(plan.changes.length,2);
c.applyProfile({harnesses:['claude','codex'],project:'',values:vals});
let md=fs.readFileSync(path.join(H,'.claude/CLAUDE.md'),'utf8');
assert(md.startsWith('# My rules\n\n- keep this\n')&&md.includes('under 40 lines')&&md.includes('- Never push'));
c.applyProfile({harness:'claude',project:'',values:{verbosity:'caveman'}});
md=fs.readFileSync(path.join(H,'.claude/CLAUDE.md'),'utf8');
assert.strictEqual(md.match(/agentdeck:start/g).length,1); assert(!md.includes('40 lines')); assert(md.includes('keep this'));
c.applyProfile({harness:'claude',project:'',values:{}});
assert.strictEqual(fs.readFileSync(path.join(H,'.claude/CLAUDE.md'),'utf8'),'# My rules\n\n- keep this\n');
assert.deepStrictEqual(c.getProfile({harness:'codex',project:''}).values,vals);
let r=c.planProfile({harness:'claude',project:'',native:{effortLevel:'high','permissions.defaultMode':'bypassPermissions','env.BASH_MAX_OUTPUT_LENGTH':'10000',model:''}});
assert.strictEqual(r.warnings.length,1);
c.applyProfile({harness:'claude',project:'',native:{effortLevel:'high','permissions.defaultMode':'plan','env.BASH_MAX_OUTPUT_LENGTH':'10000',cleanupPeriodDays:'30',alwaysThinkingEnabled:true}});
let st=JSON.parse(fs.readFileSync(path.join(H,'.claude/settings.json'),'utf8'));
assert.deepStrictEqual(st,{permissions:{allow:['Bash(ls)'],defaultMode:'plan'},env:{FOO:'1',BASH_MAX_OUTPUT_LENGTH:'10000'},effortLevel:'high',alwaysThinkingEnabled:true,cleanupPeriodDays:30});
c.applyProfile({harness:'claude',project:'',native:{effortLevel:''}});
assert(!('effortLevel' in JSON.parse(fs.readFileSync(path.join(H,'.claude/settings.json'),'utf8'))));
c.applyProfile({harness:'codex',project:'',native:{model_verbosity:'low',model_auto_compact_token_limit:'120000',model:'gpt-5.5'}});
const toml=fs.readFileSync(path.join(H,'.codex/config.toml'),'utf8');
assert(/^model = "gpt-5.5"\nmodel_verbosity = "low"\nmodel_auto_compact_token_limit = 120000\n\n\[projects/.test(toml),toml);
assert.strictEqual(c.getProfile({harness:'codex',project:''}).native.find(n=>n.key==='model_verbosity').value,'low');
c.applyProfile({harness:'claude',project:proj,values:{scope:'surgical'}});
assert(fs.readFileSync(path.join(proj,'CLAUDE.md'),'utf8').includes('Touch only'));
assert.throws(()=>c.getProfile({harness:'claude',project:'C:\Windows'}),/not a project/);
const skill={type:'skills',scope:'global',name:'Review Checklist',description:'Review: a diff',body:'# Hi',fields:{'allowed-tools':'Read, Grep'}};
let ip=c.planItem({...skill,harnesses:['claude','codex','gemini','aider']});
assert.strictEqual(ip.changes.length,3); assert.strictEqual(ip.warnings.length,1);
c.saveItem({...skill,harnesses:['claude','codex','gemini']});
const sk=c.listItems({harness:'claude',project:''}).skills[0];
assert.strictEqual(sk.name,'review-checklist'); assert.strictEqual(sk.description,'Review: a diff'); assert.deepStrictEqual(sk.fields['allowed-tools'],['Read','Grep']);
assert(!fs.readFileSync(path.join(H,'.agents/skills/review-checklist/SKILL.md'),'utf8').includes('allowed-tools'));
c.saveItem({type:'agents',harnesses:['claude'],scope:'project',project:proj,name:'tester',description:'Runs tests',body:'You run tests.',fields:{model:'haiku',tools:'Bash, Read'}});
const ag=c.listItems({harness:'claude',project:proj}).agents[0];
assert.strictEqual(ag.scope,'project'); assert.strictEqual(ag.fields.model,'haiku');
c.saveItem({type:'agents',path:ag.path,name:'tester',description:'Runs tests fast',body:'You run tests.',fields:{model:'sonnet'}});
assert.strictEqual(c.listItems({harness:'claude',project:proj}).agents[0].description,'Runs tests fast');
c.deleteItem({path:sk.path}); assert(!fs.existsSync(path.dirname(sk.path)));
assert.throws(()=>c.planItem({path:path.join(H,'.claude/settings.json'),remove:true}),/not an agent/);
assert.throws(()=>c.readFile({path:path.join(H,'.ssh/id_rsa')}),/not one of/);
c.writeFile({path:path.join(H,'.claude/CLAUDE.md'),content:'changed\n'});
const b=c.listBackups().backups; assert(b.length>5);
c.restoreBackup({file:b.find(x=>x.original.endsWith('CLAUDE.md')&&!x.isDir).file});
assert.strictEqual(fs.readFileSync(path.join(H,'.claude/CLAUDE.md'),'utf8'),'# My rules\n\n- keep this\n');
c.savePreset({name:'mine',values:vals}); assert(c.listPresets().presets.mine);
console.log('ALL OK. backups:',b.length,'home:',H);
